### ISSUE TITLE
lenovo EFI

### ISSUE THREAD

**Issue by y655r** [ittat/MacOS_OpenCore_Surface_pro_3#2]
谢谢您了，我电脑是yoga11s 在论坛上只找到了yoga13的EFI，两个的配置很类似（大概只有CPU不同），         [https://bbs.pcbeta.com/viewthread-1859371-1-1.html](https://bbs.pcbeta.com/viewthread-1859371-1-1.html)
m17124267520_20@163.com

**Comment by ittat** [comment]
[yoga13EFI.zip](https://github.com/ittat/MacOS_OpenCore_Surface_pro_3/files/8649163/yoga13EFI.zip)

**Comment by y655r** [comment]
您好，谢谢您的帮助。已经下载了，正在测试，一直卡代码“_service exited with abnormal code 1_”，后重启。

**Comment by y655r** [comment]
您好，能再帮我下载个EFI文件吗？[https://bbs.pcbeta.com/viewthread-1552225-1-2.html](url)谢谢

**Comment by ittat** [comment]
[Uploading Lenovo-Ideapad-Yoga13-v12.5.zip…]()

**Comment by ittat** [comment]
前段时间没有留意到信息 [Lenovo-Ideapad-Yoga13-v12.5.zip](https://github.com/ittat/MacOS_OpenCore_Surface_pro_3/files/8759691/Lenovo-Ideapad-Yoga13-v12.5.zip)

**Comment by y655r** [comment]
感谢您帮助下载，网络上找不到yoga11s的EFI，试用yoga13的EFI总是进不了安装界面，似乎是显卡驱动不了，暂时没时间弄了。


| |
zm_20
|
|
***@***.***
|
签名由网易邮箱大师定制
On 5/24/2022 ***@***.***> wrote：

Lenovo-Ideapad-Yoga13-v12.5.zip
